export enum ScreenType {
  Home = 0,
  Skirmish = 1,
  QuickGame = 2,
  CustomGame = 3,
  Login = 4,
  NewAccount = 5,
  Lobby = 6,
  MapSelection = 7,
  Ladder = 8,
  LadderRules = 9,
  ReplaySelection = 10,
  ModSelection = 11,
  Score = 12,
  InfoAndCredits = 13,
  PatchNotes = 14,
  Credits = 15,
  Options = 16,
  OptionsSound = 17,
  OptionsKeyboard = 18,
  OptionsStorage = 19,
}