export enum OrderType {
  Move = 0,
  ForceMove = 1,
  Attack = 2,
  ForceAttack = 3,
  AttackMove = 4,
  Guard = 5,
  GuardArea = 6,
  Capture = 7,
  Occupy = 8,
  Deploy = 9,
  DeploySelected = 10,
  Stop = 11,
  Cheer = 12,
  Dock = 13,
  Gather = 14,
  Repair = 15,
  Scatter = 16,
  EnterTransport = 17,
  PlaceBomb = 18
}