System.register(
  "gui/screen/game/worldInteraction/keyboard/KeyCommandType",
  [],
  function (t, e) {
    "use strict";
    let KeyCommandType: any;
    e && e.id;
    return {
      setters: [],
      execute: function () {
        let e: any;
        ((e = KeyCommandType || t("KeyCommandType", (KeyCommandType = {})))).CenterView = "CenterView",
          (e.Options = "Options"),
          (e.CenterOnRadarEvent = "CenterOnRadarEvent"),
          (e.RightSidebarUp = "RightSidebarUp"),
          (e.RightSidebarDown = "RightSidebarDown"),
          (e.LeftSidebarDown = "LeftSidebarDown"),
          (e.LeftSidebarUp = "LeftSidebarUp"),
          (e.Delete = "Delete"),
          (e.TeamSelect_10 = "TeamSelect_10"),
          (e.TeamSelect_1 = "TeamSelect_1"),
          (e.TeamSelect_2 = "TeamSelect_2"),
          (e.TeamSelect_3 = "TeamSelect_3"),
          (e.TeamSelect_4 = "TeamSelect_4"),
          (e.TeamSelect_5 = "TeamSelect_5"),
          (e.TeamSelect_6 = "TeamSelect_6"),
          (e.TeamSelect_7 = "TeamSelect_7"),
          (e.TeamSelect_8 = "TeamSelect_8"),
          (e.TeamSelect_9 = "TeamSelect_9"),
          (e.ToggleAlliance = "ToggleAlliance"),
          (e.PlaceBeacon = "PlaceBeacon"),
          (e.AllToCheer = "AllToCheer"),
          (e.DeployObject = "DeployObject"),
          (e.InfantryTab = "InfantryTab"),
          (e.Follow = "Follow"),
          (e.GuardObject = "GuardObject"),
          (e.CenterBase = "CenterBase"),
          (e.ToggleRepair = "ToggleRepair"),
          (e.ToggleSell = "ToggleSell"),
          (e.PreviousObject = "PreviousObject"),
          (e.NextObject = "NextObject"),
          (e.CombatantSelect = "CombatantSelect"),
          (e.StructureTab = "StructureTab"),
          (e.UnitTab = "UnitTab"),
          (e.StopObject = "StopObject"),
          (e.TypeSelect = "TypeSelect"),
          (e.PageUser = "PageUser"),
          (e.DefenseTab = "DefenseTab"),
          (e.ScatterObject = "ScatterObject"),
          (e.HealthNav = "HealthNav"),
          (e.VeterancyNav = "VeterancyNav"),
          (e.PlanningMode = "PlanningMode"),
          (e.View1 = "View1"),
          (e.View2 = "View2"),
          (e.View3 = "View3"),
          (e.View4 = "View4"),
          (e.Taunt_1 = "Taunt_1"),
          (e.Taunt_2 = "Taunt_2"),
          (e.Taunt_3 = "Taunt_3"),
          (e.Taunt_4 = "Taunt_4"),
          (e.Taunt_5 = "Taunt_5"),
          (e.Taunt_6 = "Taunt_6"),
          (e.Taunt_7 = "Taunt_7"),
          (e.Taunt_8 = "Taunt_8"),
          (e.RaiseCell = "RaiseCell"),
          (e.LowerCell = "LowerCell"),
          (e.DeleteObject = "DeleteObject"),
          (e.TeamAddSelect_10 = "TeamAddSelect_10"),
          (e.TeamAddSelect_1 = "TeamAddSelect_1"),
          (e.TeamAddSelect_2 = "TeamAddSelect_2"),
          (e.TeamAddSelect_3 = "TeamAddSelect_3"),
          (e.TeamAddSelect_4 = "TeamAddSelect_4"),
          (e.TeamAddSelect_5 = "TeamAddSelect_5"),
          (e.TeamAddSelect_6 = "TeamAddSelect_6"),
          (e.TeamAddSelect_7 = "TeamAddSelect_7"),
          (e.TeamAddSelect_8 = "TeamAddSelect_8"),
          (e.TeamAddSelect_9 = "TeamAddSelect_9"),
          (e.IonStorm = "IonStorm"),
          (e.TeamCreate_10 = "TeamCreate_10"),
          (e.TeamCreate_1 = "TeamCreate_1"),
          (e.TeamCreate_2 = "TeamCreate_2"),
          (e.TeamCreate_3 = "TeamCreate_3"),
          (e.TeamCreate_4 = "TeamCreate_4"),
          (e.TeamCreate_5 = "TeamCreate_5"),
          (e.TeamCreate_6 = "TeamCreate_6"),
          (e.TeamCreate_7 = "TeamCreate_7"),
          (e.TeamCreate_8 = "TeamCreate_8"),
          (e.TeamCreate_9 = "TeamCreate_9"),
          (e.ScreenCapture = "ScreenCapture"),
          (e.ToggleElite = "ToggleElite"),
          (e.FreeMoney = "FreeMoney"),
          (e.IonBlast = "IonBlast"),
          (e.LightningBolt = "LightningBolt"),
          (e.ToggleMono = "ToggleMono"),
          (e.NukeExplosion = "NukeExplosion"),
          (e.BuildCheat = "BuildCheat"),
          (e.ToggleShroud = "ToggleShroud"),
          (e.ToggleThreatPrint = "ToggleThreatPrint"),
          (e.SpecialWeapons = "SpecialWeapons"),
          (e.ToggleAttackFriendlies = "ToggleAttackFriendlies"),
          (e.SetView1 = "SetView1"),
          (e.SetView2 = "SetView2"),
          (e.SetView3 = "SetView3"),
          (e.SetView4 = "SetView4"),
          (e.Explosion = "Explosion"),
          (e.PrevMonoPage = "PrevMonoPage"),
          (e.NextMonoPage = "NextMonoPage"),
          (e.TeamCenter_10 = "TeamCenter_10"),
          (e.TeamCenter_1 = "TeamCenter_1"),
          (e.TeamCenter_2 = "TeamCenter_2"),
          (e.TeamCenter_3 = "TeamCenter_3"),
          (e.TeamCenter_4 = "TeamCenter_4"),
          (e.TeamCenter_5 = "TeamCenter_5"),
          (e.TeamCenter_6 = "TeamCenter_6"),
          (e.TeamCenter_7 = "TeamCenter_7"),
          (e.TeamCenter_8 = "TeamCenter_8"),
          (e.TeamCenter_9 = "TeamCenter_9"),
          (e.ToggleMarbleMadness = "ToggleMarbleMadness"),
          (e.ForceWin = "ForceWin"),
          (e.BailOut = "BailOut"),
          (e.SuperExplosion = "SuperExplosion"),
          (e.SidebarPageUp = "SidebarPageUp"),
          (e.SidebarUp = "SidebarUp"),
          (e.SidebarPageDown = "SidebarPageDown"),
          (e.SidebarDown = "SidebarDown"),
          (e.ToggleFps = "ToggleFps"),
          (e.Scoreboard = "Scoreboard");
      },
    };
  },
);
